/*
 * AquaChain Device Certificates
 * 
 * This file contains the AWS IoT device certificates.
 * Replace the placeholder certificates with your actual device certificates.
 * 
 * To generate certificates:
 * 1. Run: python provision-device.py AquaChain-Device-001
 * 2. Copy the generated certificates into this file
 * 3. Update the DEVICE_ID in config.h to match your device
 */

#ifndef CERTIFICATES_H
#define CERTIFICATES_H

// Amazon Root CA 1 (valid for all AWS IoT endpoints)
const char aws_root_ca[] PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
MIIDQTCCAimgAwIBAgITBmyfz5m/jAo54vB4ikPmljZbyjANBgkqhkiG9w0BAQsF
ADA5MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRkwFwYDVQQDExBBbWF6
b24gUm9vdCBDQSAxMB4XDTE1MDUyNjAwMDAwMFoXDTM4MDExNzAwMDAwMFowOTEL
MAkGA1UEBhMCVVMxDzANBgNVBAoTBkFtYXpvbjEZMBcGA1UEAxMQQW1hem9uIFJv
b3QgQ0EgMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJ4gHHKeNXj
ca9HgFB0fW7Y14h29Jlo91ghYPl0hAEvrAIthtOgQ3pOsqTQNroBvo3bSMgHFzZM
9O6II8c+6zf1tRn4SWiw3te5djgdYZ6k/oI2peVKVuRF4fn9tBb6dNqcmzU5L/qw
IFAGbHrQgLKm+a/sRxmPUDgH3KKHOVj4utWp+UhnMJbulHheb4mjUcAwhmahRWa6
VOujw5H5SNz/0egwLX0tdHA114gk957EWW67c4cX8jJGKLhD+rcdqsq08p8kDi1L
93FcXmn/6pUCyziKrlA4b9v7LWIbxcceVOF34GfID5yHI9Y/QCB/IIDEgEw+OyQm
jgSubJrIqg0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMC
AYYwHQYDVR0OBBYEFIQYzIU07LwMlJQuCFmcx7IQTgoIMA0GCSqGSIb3DQEBCwUA
A4IBAQCY8jdaQZChGsV2USggNiMOruYou6r4lK5IpDB/G/wkjUu0yKGX9rbxenDI
U5PMCCjjmCXPI6T53iHTfIuJruydjsw2hUwsOBYy7n6Klf+z/qH8F4zTMITTMBmR
TqhFk0FhFLPgraGxVp+5iYaAoucbAurcxO0kn6+bW+2E4UXfQHI6A+1xzU52sMpT
1tJg6+6ATyQFLEFHmMP7DslHZfi7t8n8F5Z1kI4zI2FKsAHcEFbAD5lIGe7aHgSl
nDqBHJp7v9s0u3Slxs4T7ex2Ks2cHwNbuuTqNiHqYSK1dM0T+HdybqZSayaVNhqx
RGTBtb9HI79Oj/BqVqth1S9K
-----END CERTIFICATE-----
)EOF";

// Device Certificate (REPLACE WITH YOUR ACTUAL CERTIFICATE)
const char aws_device_cert[] PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
REPLACE_WITH_YOUR_DEVICE_CERTIFICATE
This is a placeholder. You must replace this with your actual device certificate
generated by AWS IoT Core. Use the provision-device.py script to generate
certificates for your device.

To get your certificate:
1. Run: python provision-device.py AquaChain-Device-001
2. Copy the contents of the generated certificate file
3. Paste it here, replacing this placeholder text
-----END CERTIFICATE-----
)EOF";

// Device Private Key (REPLACE WITH YOUR ACTUAL PRIVATE KEY)
const char aws_device_private_key[] PROGMEM = R"EOF(
-----BEGIN RSA PRIVATE KEY-----
REPLACE_WITH_YOUR_DEVICE_PRIVATE_KEY
This is a placeholder. You must replace this with your actual device private key
generated by AWS IoT Core. Use the provision-device.py script to generate
the private key for your device.

To get your private key:
1. Run: python provision-device.py AquaChain-Device-001
2. Copy the contents of the generated private key file
3. Paste it here, replacing this placeholder text

IMPORTANT: Keep this private key secure and never share it publicly!
-----END RSA PRIVATE KEY-----
)EOF";

#endif // CERTIFICATES_H